#! /bin/sh

cd "/home/pi/"

echo "=> Starting mode selector...\n"
sudo cp amt_modeselector.sh /etc/init.d/
sudo chmod +x /etc/init.d/amt_modeselector.sh

sudo update-rc.d amt_modeselector.sh defaults
sudo /etc/init.d/amt_modeselector.sh start

echo "Mode selector installed.\n"
