#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping mode selector...\n"
sudo update-rc.d amt_modeselector.sh remove
sudo /etc/init.d/amt_modeselector.sh stop

echo "=> Removing mode selector...\n"
sudo rm -rf /usr/local/bin/amt_modeselector.py 
sudo rm -rf /etc/init.d/amt_modeselector.sh 

echo "Mode selector uninstalled.\n"
